apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - host: minikube.ingress
    http:
      paths:
      - path: /(.*)
        backend:
          serviceName: webapp-srv
          servicePort: 32777 