apiVersion: v1
kind: Service
metadata:
    name: webapp-srv
spec:
    ports:
        - port: 32777
          targetPort: 80
          protocol: TCP
          name: http
    selector:
        app: webapp-pod
    type: NodePort
